import os

os.system('python KISA_hour.py --mode train --filepath train_2020-07.csv --mark KISA_wo0 --gamma 0.3 --num_of_cluster 1')
os.system('python KISA_hour.py --mode train --filepath train_2020-07.csv --mark KISA_wo1 --gamma 0.3 --num_of_cluster 1')
os.system('python KISA_hour.py --mode train --filepath train_2020-07.csv --mark KISA_wo2 --gamma 0.3 --num_of_cluster 1')
os.system('python KISA_hour.py --mode train --filepath train_2020-07.csv --mark KISA_wo3 --gamma 0.3 --num_of_cluster 1')
os.system('python KISA_hour.py --mode train --filepath train_2020-07.csv --mark KISA_wo4 --gamma 0.3 --num_of_cluster 1')
os.system('python KISA_hour.py --mode train --filepath train_2020-07.csv --mark KISA_wo5 --gamma 0.3 --num_of_cluster 1')



# os.system('python KISA_type.py --mode train --filepath train_2020-07.csv --mark KISA_type0 --gamma 0.3')
# os.system('python KISA_type.py --mode train --filepath train_2020-07.csv --mark KISA_type1 --gamma 0.3')
# os.system('python KISA_type.py --mode train --filepath train_2020-07.csv --mark KISA_type2 --gamma 0.3')

# os.system('python da_KL.py --mode train --filepath train_2020-07.csv --mark da_KL0 --gamma 0.1 --gamma_aux 0.1')
# os.system('python da_KL.py --mode train --filepath train_2020-07.csv --mark da_KL1 --gamma 0.1 --gamma_aux 0.1')
# os.system('python da_KL.py --mode train --filepath train_2020-07.csv --mark da_KL2 --gamma 0.1 --gamma_aux 0.1')
# os.system('python da_KL.py --mode train --filepath train_2020-07.csv --mark da_KL3 --gamma 0.1 --gamma_aux 0.1')
# os.system('python da_KL.py --mode train --filepath train_2020-07.csv --mark da_KL4 --gamma 0.1 --gamma_aux 0.1')
# os.system('python da_KL.py --mode train --filepath train_2020-07.csv --mark da_KL5 --gamma 0.1 --gamma_aux 0.1')

# os.system('python share_lstm.py --mode train --filepath train_2020-07.csv --direct True --mark lstm0')
# os.system('python share_lstm.py --mode train --filepath train_2020-07.csv --direct True --mark lstm1')
# os.system('python share_lstm.py --mode train --filepath train_2020-07.csv --direct True --mark lstm2')
# os.system('python share_lstm.py --mode train --filepath train_2020-07.csv --mark finetune0')
# os.system('python share_lstm.py --mode train --filepath train_2020-07.csv --mark finetune1')
# os.system('python share_lstm.py --mode train --filepath train_2020-07.csv --mark finetune2')

# os.system('python da_MMD.py --mode train --filepath train_2020-07.csv --mark da_MMD0 --gamma 0.1')
# os.system('python da_MMD.py --mode train --filepath train_2020-07.csv --mark da_MMD1 --gamma 0.1')
# os.system('python da_MMD.py --mode train --filepath train_2020-07.csv --mark da_MMD2 --gamma 0.1')
# # os.system('python da_coral.py --mode train --filepath train_2020-07.csv --mark da_coral0 --gamma 20000')
# # os.system('python da_coral.py --mode train --filepath train_2020-07.csv --mark da_coral1 --gamma 20000')
# # os.system('python da_coral.py --mode train --filepath train_2020-07.csv --mark da_coral2 --gamma 20000')
# os.system('python da_transfer_HEN.py --mode train --filepath train_2020-07.csv --mark da_HEN0 --gamma 0.5')
# os.system('python da_transfer_HEN.py --mode train --filepath train_2020-07.csv --mark da_HEN1 --gamma 0.5')
# os.system('python da_transfer_HEN.py --mode train --filepath train_2020-07.csv --mark da_HEN2 --gamma 0.5')
# os.system('python DSAN.py --mode train --filepath train_2020-07.csv --mark dsan0 --gamma 0.1')
# os.system('python DSAN.py --mode train --filepath train_2020-07.csv --mark dsan1 --gamma 0.1')
# os.system('python DSAN.py --mode train --filepath train_2020-07.csv --mark dsan2 --gamma 0.1')
# os.system('python KISA_type.py --mode train --filepath train_2020-07.csv --mark KISA_type0 --gamma 0.3')
# os.system('python KISA_type.py --mode train --filepath train_2020-07.csv --mark KISA_type1 --gamma 0.3')
# os.system('python KISA_type.py --mode train --filepath train_2020-07.csv --mark KISA_type2 --gamma 0.3')

# os.system('python KISA_hour.py --mode train --filepath train_2020-07.csv --mark KISA_hour0 --gamma 0.3')
# os.system('python KISA_hour.py --mode train --filepath train_2020-07.csv --mark KISA_hour1 --gamma 0.3')
# os.system('python KISA_hour.py --mode train --filepath train_2020-07.csv --mark KISA_hour2 --gamma 0.3')

# os.system('python KISA_MMD_type.py --mode train --filepath train_2020-07.csv --mark KISA_MMD_type0 --gamma 0.3')
# os.system('python KISA_MMD_type.py --mode train --filepath train_2020-07.csv --mark KISA_MMD_type1 --gamma 0.3')
# os.system('python KISA_MMD_type.py --mode train --filepath train_2020-07.csv --mark KISA_MMD_type2 --gamma 0.3')

# os.system('python KISA_MMD_hour.py --mode train --filepath train_2020-07.csv --mark KISA_MMD_hour0 --gamma 0.3')
# os.system('python KISA_MMD_hour.py --mode train --filepath train_2020-07.csv --mark KISA_MMD_hour1 --gamma 0.3')
# os.system('python KISA_MMD_hour.py --mode train --filepath train_2020-07.csv --mark KISA_MMD_hour2 --gamma 0.3')
# os.system('python KISA_PM_type.py --mode train --filepath train_2020-07.csv --mark KISA_PM_type0 --gamma 0.3')
# os.system('python KISA_PM_type.py --mode train --filepath train_2020-07.csv --mark KISA_PM_type1 --gamma 0.3')
# os.system('python KISA_PM_type.py --mode train --filepath train_2020-07.csv --mark KISA_PM_type2 --gamma 0.3')
# os.system('python KISA_PM_hour.py --mode train --filepath train_2020-07.csv --mark KISA_PM_hour0 --gamma 0.3')
# os.system('python KISA_PM_hour.py --mode train --filepath train_2020-07.csv --mark KISA_PM_hour1 --gamma 0.3')
# os.system('python KISA_PM_hour.py --mode train --filepath train_2020-07.csv --mark KISA_PM_hour2 --gamma 0.3')


'''os.system('python share_lstm.py --mode train --filepath train_2020-03.csv --direct True --mark lstm0')
os.system('python share_lstm.py --mode train --filepath train_2020-03.csv --direct True --mark lstm1')
os.system('python share_lstm.py --mode train --filepath train_2020-03.csv --direct True --mark lstm2')
os.system('python share_lstm.py --mode train --filepath train_2020-03.csv --mark finetune0')
os.system('python share_lstm.py --mode train --filepath train_2020-03.csv --mark finetune1')
os.system('python share_lstm.py --mode train --filepath train_2020-03.csv --mark finetune2')
os.system('python da_MMD.py --mode train --filepath train_2020-03.csv --mark da_MMD0 --gamma 0.1')
os.system('python da_MMD.py --mode train --filepath train_2020-03.csv --mark da_MMD1 --gamma 0.1')
os.system('python da_MMD.py --mode train --filepath train_2020-03.csv --mark da_MMD2 --gamma 0.1')
os.system('python da_coral.py --mode train --filepath train_2020-03.csv --mark da_coral0 --gamma 20000')
os.system('python da_coral.py --mode train --filepath train_2020-03.csv --mark da_coral1 --gamma 20000')
os.system('python da_coral.py --mode train --filepath train_2020-03.csv --mark da_coral2 --gamma 20000')
os.system('python da_transfer_HEN.py --mode train --filepath train_2020-03.csv --mark da_HEN0 --gamma 0.5')
os.system('python da_transfer_HEN.py --mode train --filepath train_2020-03.csv --mark da_HEN1 --gamma 0.5')
os.system('python da_transfer_HEN.py --mode train --filepath train_2020-03.csv --mark da_HEN2 --gamma 0.5')
 
os.system('python DSAN.py --mode train --filepath train_2020-03.csv --mark dsan0 --gamma 0.1')
os.system('python DSAN.py --mode train --filepath train_2020-03.csv --mark dsan1 --gamma 0.1')
os.system('python DSAN.py --mode train --filepath train_2020-03.csv --mark dsan2 --gamma 0.1')
os.system('python KISA_type.py --mode train --filepath train_2020-03.csv --mark KISA_type0 --gamma 0.3')
os.system('python KISA_type.py --mode train --filepath train_2020-03.csv --mark KISA_type1 --gamma 0.3')
os.system('python KISA_type.py --mode train --filepath train_2020-03.csv --mark KISA_type2 --gamma 0.3')

os.system('python KISA_hour.py --mode train --filepath train_2020-03.csv --mark KISA_hour0 --gamma 0.3')
os.system('python KISA_hour.py --mode train --filepath train_2020-03.csv --mark KISA_hour1 --gamma 0.3')
os.system('python KISA_hour.py --mode train --filepath train_2020-03.csv --mark KISA_hour2 --gamma 0.3')

os.system('python KISA_MMD_type.py --mode train --filepath train_2020-03.csv --mark KISA_MMD_type0 --gamma 0.3')
os.system('python KISA_MMD_type.py --mode train --filepath train_2020-03.csv --mark KISA_MMD_type1 --gamma 0.3')
os.system('python KISA_MMD_type.py --mode train --filepath train_2020-03.csv --mark KISA_MMD_type2 --gamma 0.3')

os.system('python KISA_MMD_hour.py --mode train --filepath train_2020-03.csv --mark KISA_MMD_hour0 --gamma 0.3')
os.system('python KISA_MMD_hour.py --mode train --filepath train_2020-03.csv --mark KISA_MMD_hour1 --gamma 0.3')
os.system('python KISA_MMD_hour.py --mode train --filepath train_2020-03.csv --mark KISA_MMD_hour2 --gamma 0.3')
os.system('python KISA_PM_type.py --mode train --filepath train_2020-03.csv --mark KISA_PM_type0 --gamma 0.3')
os.system('python KISA_PM_type.py --mode train --filepath train_2020-03.csv --mark KISA_PM_type1 --gamma 0.3')
os.system('python KISA_PM_type.py --mode train --filepath train_2020-03.csv --mark KISA_PM_type2 --gamma 0.3')
os.system('python KISA_PM_hour.py --mode train --filepath train_2020-03.csv --mark KISA_PM_hour0 --gamma 0.3')
os.system('python KISA_PM_hour.py --mode train --filepath train_2020-03.csv --mark KISA_PM_hour1 --gamma 0.3')
os.system('python KISA_PM_hour.py --mode train --filepath train_2020-03.csv --mark KISA_PM_hour2 --gamma 0.3')'''